config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    #path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('', include("ibmn.news.urls")),
    path("accounts/", include("ibmn.users.urls", namespace="users")),
    path("trending/", include("ibmn.trending.urls", namespace="trending")),
    path("breaking/", include("ibmn.breaking.urls", namespace="breaking")),
    path("bignews/", include("ibmn.bignews.urls", namespace="bignews")),
    path("categories/", include("ibmn.categories.urls", namespace="categories")),
    path("ckeditor/", include('ckeditor_uploader.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ibmn/bignews/urls.py
from django.urls import include, path
from django.conf.urls import url


from ibmn.bignews.views import (bignews_create_view, bignews_update_view, big_news_details_view,
                                bignews_manager_delete_view , bignews_list_view, big_news_reply_page)


app_name = "bignews"
urlpatterns = [
    path("create/", view=bignews_create_view, name="bignews_create"),
    path('list_news/', view=bignews_list_view, name='bignews_list_post'),
    path('update/<uuid:uuid>/', view=bignews_update_view, name='bignews_update_news'),
    path('delete/<uuid:uuid>/', view= bignews_manager_delete_view, name='bignews_delete_news'),
    path("<slug:slug>/", view=big_news_details_view, name="bignews_detail"),
    path('big_comment/reply/', big_news_reply_page, name="bignews_reply"),



]

ibmn/breaking/urls.py
from django.urls import include, path
from django.conf.urls import url


from ibmn.breaking.views import ( break_list_view, break_create_view,
                                 break_update_view, breaking_manager_delete_view)


app_name = "breaking"
urlpatterns = [
    path("create/", view=break_create_view, name="break_create"),
    path('list/', view=break_list_view, name='break_list'),
    path('update/<uuid:uuid>/', view=break_update_view, name='break_update_news'),
    path('delete/<uuid:uuid>/', view=breaking_manager_delete_view, name='break_delete_news'),

    #path("<slug:slug>/", view=news_detail_view, name="news_detail"),

]

ibmn/news/urls.py
from django.urls import include, path
from django.conf.urls import url


from ibmn.news.views import (
                            home_view , manager_home_view, news_create_view,  manager_list_post_view, 
                             manager_update_view, manager_delete_view, news_details_view, reply_page,
                             search_list_news_view
                            )


app_name = "news"
urlpatterns = [
    path('', view=home_view, name="home"),
    path("create_news/", view=news_create_view, name="create"),
    path('list/', view=manager_list_post_view, name='manager_list_post'),
    path("home/", view= manager_home_view, name="manager_home"),
    path('update/<uuid:uuid>/', view=manager_update_view, name='manager_update_news'),
    path('delete/<uuid:uuid>/', view=manager_delete_view, name='manager_delete_news'),
    #path("<slug:tag_slug>/", view=news_details_view, name="news_tag_detail"),
    path("<slug:slug>/", view=news_details_view, name="news_detail"),
    path('comment/reply/', reply_page, name="reply"),
    path('list/', view=search_list_news_view, name='search'),


]

ibmn/trending/urls.py
from django.urls import include, path
from django.conf.urls import url


from ibmn.trending.views import (TrendCreateView, trend_update_view, trend_list_view,
                                  trending_news_details_view,trend_manager_delete_view ,
                                  trending_news_reply_page
                                 )


app_name = "trending"
urlpatterns = [
    path("create/", TrendCreateView.as_view(), name="trending_create"),
    path('list_trend/', view=trend_list_view, name='trend_list_post'),
    path('update/<uuid:uuid>/', view=trend_update_view, name='trend_update_news'),
    path('delete/<uuid:uuid>/', view=trend_manager_delete_view, name='trend_delete_news'),
    path("<slug:slug>/", view=trending_news_details_view, name="trendnews_detail"),
    path('trend_comment/reply/', trending_news_reply_page, name="trendnews_reply"),


    #path("<slug:slug>/", view=news_detail_view, name="news_detail"),

]

ibmn/users/urls.py
from django.urls import path
from ibmn.users.views import LoginView, logout_view



app_name = "users"
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', view=logout_view, name='logout'),

    
]

ibmn/breaking/models.py
import uuid
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


# Create your models here.

class Breaking(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    text = models.CharField(max_length=300, default='text')
    image = models.ImageField(upload_to='profile_image', null=True)         
    created_at = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.text

ibmn/bignews/forms.py
from unittest.util import _MAX_LENGTH
from django import forms
from django.forms import ModelChoiceField
from django.contrib.auth import authenticate
from ibmn.bignews.models import Bignews
from ibmn.categories.models import Category

from mptt.forms import TreeNodeChoiceField 
from ckeditor_uploader.widgets import  CKEditorUploadingWidget


class CreateBignewsForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text',  'data-constraints':'@Required'}))
    short_txt = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text','data-constraints':'@Required'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'id':'formFile','type':'file', 'class':'control'}))
    #slug = forms.SlugField(widget=forms.TextInput(attrs={"class": "form-control", 'type':'text'}))
   # pub_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'form-control'}))
    #category_name = forms.ModelChoiceField(queryset=Category.objects.all())
    body_txt =forms.CharField(widget=CKEditorUploadingWidget(attrs={'class':'form-control', 'rows':'5', 'cols':'50','data-constraints':'@Required'}))
   
   

    class Meta:
            model = Bignews
            fields = [
                    "title",
                    "short_txt",
                    "body_txt",
                    #"slug",
                   #"pub_date",
                    "image",
                    "category",
                    "tags"
                    ]

    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'] = forms.ModelChoiceField(queryset=Category.objects.all())

    
          

class EditBigNewsForm(forms.ModelForm):

    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text',  'data-constraints':'@Required'}))
    short_txt = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text','data-constraints':'@Required'}))
    #timestamp = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'id':'formFile','type':'file', 'class':'control'}))
    slug = forms.SlugField(widget=forms.TextInput(attrs={"class": "form-control", 'type':'text'}))
    #pub_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'form-control'}))
    category_name = forms.ModelChoiceField(queryset=Category.objects.all())
    body_txt =forms.CharField(widget=CKEditorUploadingWidget(attrs={'class':'form-control', 'rows':'5', 'cols':'50','data-constraints':'@Required'}))
    
    
   
   
    class Meta:
            model = Bignews
            fields = [
                    "title",
                    "short_txt",
                    "slug",
                    #"pub_date",
                    "image",
                    "category_name",
                    "body_txt",
                    "tags"
                    ]

ibmn/breaking/forms.py
from django import forms
from django.forms import ModelChoiceField
from django.contrib.auth import authenticate
from ibmn.breaking.models import Breaking

class CreateBreakForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text','data-constraints':'@Required'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'id':'formFile','type':'file', 'class':'control'}))

   
   
   
    class Meta:
            model = Breaking
            fields = [ "text",
                       "image",
                    ]

    

ibmn/comments/forms.py
import email
from django import forms
from ibmn.comments.models import Comment
from mptt.forms import TreeNodeChoiceField


class CommentForm(forms.ModelForm):


    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text',  'data-constraints':'@Required'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'email',  'data-constraints':'@Required'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'col':'40', 'row':'10', 'data-constraints':'@Required'}))



    class Meta:
        model = Comment
        fields = ('name',  'email', 'content')

ibmn/bignews/views.py
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView , DetailView, UpdateView, TemplateView, DeleteView
from ibmn.bignews.models import Bignews
from ibmn.bignews.forms import CreateBignewsForm, EditBigNewsForm
from ibmn.comments.forms import CommentForm
from ibmn.comments.models import Comment



# Create your views here.

class BignewsCreateView(View):
    template_name = 'manager_pages/bignews_add_news.html'
    form_class = CreateBignewsForm
    
    def get(self, request):
        form = self.form_class()
        message = ''
        return render(request, self.template_name, context={'form': form, 'message': message})


    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form = self.form_class()

            messages.success(request, 'Your news was successfully posted!')

        return render(request,self.template_name, {'form':form})

bignews_create_view  = BignewsCreateView.as_view()


class BignewsListPostView(LoginRequiredMixin, ListView):
    model = Bignews
    context_object_name = 'bignews_list'
    template_name = 'manager_pages/bignews_list_news.html'

bignews_list_view  =  BignewsListPostView.as_view()



class BignewsUpdateView(LoginRequiredMixin, UpdateView):
    # specify the model you want to use
    form_class = EditBigNewsForm
    model = Bignews
    template_name = 'manager_pages/bignews_update.html'

    # specify the fields
    #fields = ["title","short_txt","slug","pub_date","image","body_txt"]

    def get_object(self, queryset=None):
        return Bignews.objects.get(id=self.kwargs.get("uuid"))
  
    # can specify success url
    # url to redirect after successfully
    # updating details
    def get_success_url(self):
       return reverse("bignews:bignews_list_post")
   

bignews_update_view  = BignewsUpdateView.as_view()




class BignewsManagerDeleteView(LoginRequiredMixin, DeleteView):
    # specify the model you want to use
    model = Bignews
    template_name = 'manager_pages/bignews_delete_news.html'

    # specify the fields
    #fields = ["title","short_txt","slug","pub_date","image","body_txt"]

    def get_object(self, queryset=None):
        return Bignews.objects.get(id=self.kwargs.get("uuid"))
  
    # can specify success url
    # url to redirect after successfully
    # updating details
    def get_success_url(self):
       return reverse("bignews:bignews_list_post")
   

bignews_manager_delete_view = BignewsManagerDeleteView.as_view()






def big_news_details_view(request, slug):
    bignews=get_object_or_404(Bignews, slug=slug)

    similar_bignews =  bignews.tags.similar_objects()[:4]

    # List of active comments for this post
    bignews_comments = bignews.bignews_comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.bignews = bignews
            # Save the comment to the database
            new_comment.save()
            return redirect(bignews.get_absolute_url()+'#')
    else:
        comment_form = CommentForm()

    # List of similar posts
    
    return render(request, 'pages/bignews_details.html', {'bignews':bignews,'bignews_comments': bignews_comments,
                                                            'comment_form':comment_form, 'similar_bignews':similar_bignews
                                                        })


def big_news_reply_page(request):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            bignews_id = request.POST.get('bignews_id')  # from hidden input
            parent_id = request.POST.get('parent')  # from hidden input
            bignews_url = request.POST.get('bignews_url')  # from hidden input
            reply = form.save(commit=False)
    
            reply.post = Bignews(id=bignews_id)
            reply.parent = Comment(id=parent_id)
            reply.save()
            return redirect(bignews_url+'#')
    return redirect("/")

ibmn/breaking/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView , DetailView, UpdateView, TemplateView, DeleteView
from ibmn.breaking.models import Breaking
from ibmn.breaking.forms import CreateBreakForm
from django import forms


# Create your views here.

class BreakCreateView(View):
    template_name = 'manager_pages/break_add_news.html'
    form_class = CreateBreakForm
    
    def get(self, request):
        form = self.form_class()
        message = ''
        return render(request, self.template_name, context={'form': form, 'message': message})


    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return render(request,self.template_name, {'form':form})

break_create_view  =  BreakCreateView.as_view()




class BreakListPostView(LoginRequiredMixin, ListView):
    model = Breaking
    context_object_name = 'break_list'
    template_name = 'manager_pages/break_list_news.html'

break_list_view  =  BreakListPostView.as_view()



class BreakUpdateView(LoginRequiredMixin, UpdateView):
    # specify the model you want to use
    model = Breaking
    template_name = 'manager_pages/break_update_news.html'

    # specify the fields
    fields = ["text", "image"]

    def get_object(self, queryset=None):
        return Breaking.objects.get(id=self.kwargs.get("uuid"))
  
    # can specify success url
    # url to redirect after successfully
    # updating details
    def get_success_url(self):
       return reverse("news:manager_home")
   

break_update_view  = BreakUpdateView.as_view()




class BreakingManagerDeleteView(LoginRequiredMixin, DeleteView):
    # specify the model you want to use
    model = Breaking
    template_name = 'manager_pages/break_delete_news.html'

    # specify the fields
    #fields = ["title","short_txt","slug","pub_date","image","body_txt"]

    def get_object(self, queryset=None):
        return Breaking.objects.get(id=self.kwargs.get("uuid"))
  
    # can specify success url
    # url to redirect after successfully
    # updating details
    def get_success_url(self):
       return reverse("news:manager_home")
   

breaking_manager_delete_view = BreakingManagerDeleteView.as_view()

ibmn/templates/manager_pages/bignews_list_news.html
{% extends "base1.html" %}
{% block head_title %}Home  Manager | IBNM{% endblock %}



<body>

  {% block content %}

<!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'news:manager_home' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Add Big News</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">   
          <li>
            <a href=" {% url 'news:create' %}">
              <i class="bi bi-circle"></i><span>Add News</span>
            </a>
          </li>
          <li>
            <a href="{% url 'breaking:break_create' %}">
              <i class="bi bi-circle"></i><span> Add Breaking News</span>
            </a>
          </li>
          <li>
            <a href=" {% url 'trending:trending_create' %}">
              <i class="bi bi-circle"></i><span>Add Trending News</span>
            </a>
          </li>
          <li>
            <a href="{% url 'bignews:bignews_create' %}">
              <i class="bi bi-circle"></i><span>Add Big News</span>
            </a>
          </li>
        </ul>
      </li><!-- End Components Nav -->

      <li class="nav-item">
        <a class="nav-link " data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-journal-text"></i><span>View Big News</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="forms-nav" class="nav-content collapse show" data-bs-parent="#sidebar-nav">


          <li>
            <a href=" {% url 'news:manager_list_post' %}">
              <i class="bi bi-circle"></i><span>View News</span>
            </a>
          </li>
          <li>
            <a href="{% url 'breaking:break_list' %}">
              <i class="bi bi-circle"></i><span>View Breaking News</span>
            </a>
          </li>
          <li>
            <a href="{% url 'trending:trend_list_post' %}">
              <i class="bi bi-circle"></i><span>View Trending News</span>
            </a>
          </li>
          <li>
            <a href="{% url 'bignews:bignews_list_post' %}">
              <i class="bi bi-circle"></i><span>View Big News</span>
            </a>
          </li>



        </ul>
      </li><!-- End Forms Nav -->     
    </ul>

  </aside><!-- End Sidebar-->


  <main id="main" class="main">

    <div class="pagetitle">
      <h1> Big News</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href=" {% url 'news:manager_home' %}">Home</a></li>
          <li class="breadcrumb-item">Tables</li>
          <li class="breadcrumb-item active">Big News</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">List of  Trending News</h5>

              <!-- Table with stripped rows -->
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Start Date</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    {% for bignews in bignews_list %}
                    <th scope="row"> {{forloop.counter}} </th>
                    <td>{{bignews.title}}</td>
                    <td>{{bignews.pub_date}}</td>
                    <td> <a href="{% url 'bignews:bignews_update_news' bignews.id %}"> Edit </a></td>
                    <td> <a href="{% url 'bignews:bignews_delete_news' bignews.id %}"> Delete </a></td>
                  </tr>
                  {% endfor %}           
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>
        </div>
      </div>
    </section>

  </main><!-- End #main -->
  {% endblock %}

   
  
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>IbmnAdmin</span></strong>. All Rights Reserved
    </div>
   
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  

</body>

</html>

ibmn/templates/manager_pages/break_list_news.html
{% extends "base1.html" %}
{% block head_title %}Home  Manager | IBNM{% endblock %}



<body>

  {% block content %}

<!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'news:manager_home' %}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Add Breaking News</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">   
          <li>
            <a href=" {% url 'news:create' %}">
              <i class="bi bi-circle"></i><span>Add News</span>
            </a>
          </li>
          <li>
            <a href="{% url 'breaking:break_create' %}">
              <i class="bi bi-circle"></i><span> Add Breaking News</span>
            </a>
          </li>
          <li>
            <a href=" {% url 'trending:trending_create' %}">
              <i class="bi bi-circle"></i><span>Add Trending News</span>
            </a>
          </li>
          <li>
            <a href="{% url 'bignews:bignews_create' %}">
              <i class="bi bi-circle"></i><span>Add Big News</span>
            </a>
          </li>
        </ul>
      </li><!-- End Components Nav -->

      <li class="nav-item">
        <a class="nav-link " data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-journal-text"></i><span>View Breaking News</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="forms-nav" class="nav-content collapse show" data-bs-parent="#sidebar-nav">


          <li>
            <a href=" {% url 'news:manager_list_post' %}">
              <i class="bi bi-circle"></i><span>View News</span>
            </a>
          </li>
          <li>
            <a href="{% url 'breaking:break_list' %}">
              <i class="bi bi-circle"></i><span>View Breaking News</span>
            </a>
          </li>
          <li>
            <a href="{% url 'trending:trend_list_post' %}">
              <i class="bi bi-circle"></i><span>View Trending News</span>
            </a>
          </li>
          <li>
            <a href="{% url 'bignews:bignews_list_post' %}">
              <i class="bi bi-circle"></i><span>View Big News</span>
            </a>
          </li>



        </ul>
      </li><!-- End Forms Nav -->     
    </ul>

  </aside><!-- End Sidebar-->

  <main id="main" class="main">

    <div class="pagetitle">
      <h1> Breaking News</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href=" {% url 'news:manager_home' %}">Home</a></li>
          <li class="breadcrumb-item">Tables</li>
          <li class="breadcrumb-item active">Breaking News</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">List of Breaking News</h5>

              <!-- Table with stripped rows -->
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Text</th>
                    <th scope="col">Published Date</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    {% for break in break_list %}
                    <th scope="row"> {{forloop.counter}} </th>
                    <td>{{break.text}}</td>
                    <td>{{break.created_at}}</td>
                    <td> <a href="{% url 'breaking:break_update_news' break.id %}"> Edit </a></td>
                    <td> <a href="{% url 'breaking:break_delete_news' break.id %}"> Delete </a></td>
                  </tr>
                  {% endfor %}           
                </tbody>
              </table>
              <!-- End Table with stripped rows -->

            </div>
          </div>

         


        </div>
      </div>
    </section>

  </main><!-- End #main -->


  {% endblock %}

   
  
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>IbmnAdmin</span></strong>. All Rights Reserved
    </div>
   
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  

</body>

</html>