config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    #path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('', include("ibmn.news.urls")),
    path("accounts/", include("ibmn.users.urls", namespace="users")),
    path("trending/", include("ibmn.trending.urls", namespace="trending")),
    path("breaking/", include("ibmn.breaking.urls", namespace="breaking")),
    path("bignews/", include("ibmn.bignews.urls", namespace="bignews")),
    path("categories/", include("ibmn.categories.urls", namespace="categories")),
    path("ckeditor/", include('ckeditor_uploader.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ibmn/bignews/urls.py
from django.urls import include, path
from django.conf.urls import url


from ibmn.bignews.views import (bignews_create_view, bignews_update_view, big_news_details_view,
                                bignews_manager_delete_view , bignews_list_view, big_news_reply_page)


app_name = "bignews"
urlpatterns = [
    path("create/", view=bignews_create_view, name="bignews_create"),
    path('list_news/', view=bignews_list_view, name='bignews_list_post'),
    path('update/<uuid:uuid>/', view=bignews_update_view, name='bignews_update_news'),
    path('delete/<uuid:uuid>/', view= bignews_manager_delete_view, name='bignews_delete_news'),
    path("<slug:slug>/", view=big_news_details_view, name="bignews_detail"),
    path('big_comment/reply/', big_news_reply_page, name="bignews_reply"),



]

ibmn/categories/urls.py
from django.urls import include, path
from django.conf.urls import url



from ibmn.categories.views.categories_views import (
                                    news_cat_view, politics_cat_view, business_cat_view, sports_cat_view,
                                    health_cat_view, arts_cat_view, lifestyle_cat_view, scitech_cat_view
                                    
                                    )


from ibmn.categories.views.subcategories_views import ( 
                                 global_sub_news_cat_view, community_sub_news_cat_view, opinions_sub_news_cat_view, 
                                 africa_sub_news_cat_view, global_sub_politics_cat_view, community_sub_politics_cat_view, 
                                 opinions_sub_politics_cat_view, africa_sub_politics_cat_view,global_sub_business_cat_view, local_sub_business_cat_view,
                                 igbo_sub_business_cat_view, global_sub_sports_cat_view, local_sub_sports_cat_view,
                                 communty_sub_sports_cat_view, books_sub_arts_cat_view, movies_sub_arts_cat_view,
                                 music_sub_arts_cat_view, showbiz_sub_arts_cat_view, event_sub_arts_cat_view,
                                 food_sub_lifestyle_cat_view, culture_sub_lifestyle_cat_view,fashion_sub_lifestyle_cat_view,
                                 opinions_sub_lifestyle_cat_view, travel_sub_lifestyle_cat_view , global_sub_scitech_cat_view,
                                 web3_sub_scitech_cat_view, blockchain_sub_scitech_cat_view, ntf_sub_scitech_cat_view, crypto_sub_scitech_cat_view,
                                 community_sub_scitech_cat_view, digitech_fintech_sub_scitech_cat_view, global_sub_health_cat_view,
                                 local_sub_health_cat_view, opinions_sub_health_cat_view , community_sub_health_cat_view
                               
                               )


app_name = "categories"
urlpatterns = [
    path('news/', view=news_cat_view, name="news"),
    path('politics/', view=politics_cat_view, name="politics"),
    path('business/', view=business_cat_view, name="business"),
    path('sports/', view=sports_cat_view, name="sports"),
    path('health/', view=health_cat_view, name="health"),
    path('arts/', view=arts_cat_view, name="arts"),
    path('lifestyle/', view=lifestyle_cat_view, name="lifestyle"),
    path('scitech/', view=scitech_cat_view, name="scitech"),
    path('news/global/', view=global_sub_news_cat_view, name="news_global"),
    path('news/community/', view=community_sub_news_cat_view, name="news_community"),
    path('news/opinions/', view=opinions_sub_news_cat_view, name="news_opinions"),
    path('news/africa/', view=africa_sub_news_cat_view, name="news_africa"),
    path('politics/global/', view=global_sub_politics_cat_view, name="politics_global"),
    path('politics/community/', view=community_sub_politics_cat_view, name="politics_community"),
    path('politics/africa/', view=africa_sub_politics_cat_view, name="politics_africa"),
    path('politics/opinions/', view=opinions_sub_politics_cat_view, name="politics_opinions"),
    path('business/global/', view=global_sub_business_cat_view, name="business_global"),
    path('business/igbo/', view=igbo_sub_business_cat_view, name="business_igbo"),
    path('business/local/', view=local_sub_business_cat_view, name="business_local"),
    path('sports/global/', view=global_sub_sports_cat_view, name="sports_global"),
    path('sports/local/', view=local_sub_sports_cat_view, name="sports_local"),
    path('sports/community/', view=communty_sub_sports_cat_view, name="sports_community"),
    path('arts/books/', view=books_sub_arts_cat_view, name="arts_books"),
    path('arts/music/', view=music_sub_arts_cat_view, name="arts_music"),
    path('arts/movies/', view=movies_sub_arts_cat_view, name="arts_movies"),
    path('arts/showbiz/', view=showbiz_sub_arts_cat_view, name="arts_showbiz"),
    path('arts/events/', view=event_sub_arts_cat_view, name="arts_events"),
    path('lifestyle/food/', view=food_sub_lifestyle_cat_view, name="lifestyle_food"),
    path('lifestyle/culture/', view=culture_sub_lifestyle_cat_view, name="lifestyle_culture"),
    path('lifestyle/travel/', view=travel_sub_lifestyle_cat_view, name="lifestyle_travel"),
    path('lifestyle/fashion/', view=fashion_sub_lifestyle_cat_view, name="lifestyle_fashion"),
    path('lifestyle/opinions/', view=opinions_sub_lifestyle_cat_view, name="lifestyle_opinions"),
    path('scitech/blockchain/', view=blockchain_sub_scitech_cat_view, name="scitech_blockchain"),
    path('scitech/ntf/', view=ntf_sub_scitech_cat_view, name="scitech_ntf"),
    path('scitech/crypto/', view=crypto_sub_scitech_cat_view, name="scitech_crypto"),
    path('scitech/web3/', view=web3_sub_scitech_cat_view, name="scitech_web3"),
    path('scitech/global/', view=global_sub_scitech_cat_view, name="scitech_global"),
    path('scitech/digitech_fintech/', view=digitech_fintech_sub_scitech_cat_view, name="scitech_digitech_fintech"),
    path('scitech/community/', view=community_sub_scitech_cat_view, name="scitech_community"),
    path('health/local/', view=local_sub_health_cat_view, name="health_local"),
    path('health/global/', view=global_sub_health_cat_view, name="health_global"),
    path('health/opinions/', view=opinions_sub_health_cat_view, name="health_opinions"),
    path('health/community/', view=community_sub_health_cat_view, name="health_community"),
    
   
]

ibmn/news/urls.py
from django.urls import include, path
from django.conf.urls import url


from ibmn.news.views import (
                            home_view , manager_home_view, news_create_view,  manager_list_post_view, 
                             manager_update_view, manager_delete_view, news_details_view, reply_page,
                             search_list_news_view
                            )


app_name = "news"
urlpatterns = [
    path('', view=home_view, name="home"),
    path("create_news/", view=news_create_view, name="create"),
    path('list/', view=manager_list_post_view, name='manager_list_post'),
    path("home/", view= manager_home_view, name="manager_home"),
    path('update/<uuid:uuid>/', view=manager_update_view, name='manager_update_news'),
    path('delete/<uuid:uuid>/', view=manager_delete_view, name='manager_delete_news'),
    #path("<slug:tag_slug>/", view=news_details_view, name="news_tag_detail"),
    path("<slug:slug>/", view=news_details_view, name="news_detail"),
    path('comment/reply/', reply_page, name="reply"),
    path('list/', view=search_list_news_view, name='search'),


]

ibmn/users/urls.py
from django.urls import path
from ibmn.users.views import LoginView, logout_view



app_name = "users"
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', view=logout_view, name='logout'),

    
]

ibmn/breaking/forms.py
from django import forms
from django.forms import ModelChoiceField
from django.contrib.auth import authenticate
from ibmn.breaking.models import Breaking

class CreateBreakForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text','data-constraints':'@Required'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'id':'formFile','type':'file', 'class':'control'}))

   
   
   
    class Meta:
            model = Breaking
            fields = [ "text",
                       "image",
                    ]

    

ibmn/bignews/views.py
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView , DetailView, UpdateView, TemplateView, DeleteView
from ibmn.bignews.models import Bignews
from ibmn.bignews.forms import CreateBignewsForm, EditBigNewsForm
from ibmn.comments.forms import CommentForm
from ibmn.comments.models import Comment



# Create your views here.

class BignewsCreateView(View):
    template_name = 'manager_pages/bignews_add_news.html'
    form_class = CreateBignewsForm
    
    def get(self, request):
        form = self.form_class()
        message = ''
        return render(request, self.template_name, context={'form': form, 'message': message})


    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form = self.form_class()

            messages.success(request, 'Your news was successfully posted!')

        return render(request,self.template_name, {'form':form})

bignews_create_view  = BignewsCreateView.as_view()


class BignewsListPostView(LoginRequiredMixin, ListView):
    model = Bignews
    context_object_name = 'bignews_list'
    template_name = 'manager_pages/bignews_list_news.html'

bignews_list_view  =  BignewsListPostView.as_view()



class BignewsUpdateView(LoginRequiredMixin, UpdateView):
    # specify the model you want to use
    form_class = EditBigNewsForm
    model = Bignews
    template_name = 'manager_pages/bignews_update.html'

    # specify the fields
    #fields = ["title","short_txt","slug","pub_date","image","body_txt"]

    def get_object(self, queryset=None):
        return Bignews.objects.get(id=self.kwargs.get("uuid"))
  
    # can specify success url
    # url to redirect after successfully
    # updating details
    def get_success_url(self):
       return reverse("bignews:bignews_list_post")
   

bignews_update_view  = BignewsUpdateView.as_view()




class BignewsManagerDeleteView(LoginRequiredMixin, DeleteView):
    # specify the model you want to use
    model = Bignews
    template_name = 'manager_pages/bignews_delete_news.html'

    # specify the fields
    #fields = ["title","short_txt","slug","pub_date","image","body_txt"]

    def get_object(self, queryset=None):
        return Bignews.objects.get(id=self.kwargs.get("uuid"))
  
    # can specify success url
    # url to redirect after successfully
    # updating details
    def get_success_url(self):
       return reverse("bignews:bignews_list_post")
   

bignews_manager_delete_view = BignewsManagerDeleteView.as_view()






def big_news_details_view(request, slug):
    bignews=get_object_or_404(Bignews, slug=slug)

    similar_bignews =  bignews.tags.similar_objects()[:4]

    # List of active comments for this post
    bignews_comments = bignews.bignews_comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.bignews = bignews
            # Save the comment to the database
            new_comment.save()
            return redirect(bignews.get_absolute_url()+'#')
    else:
        comment_form = CommentForm()

    # List of similar posts
    
    return render(request, 'pages/bignews_details.html', {'bignews':bignews,'bignews_comments': bignews_comments,
                                                            'comment_form':comment_form, 'similar_bignews':similar_bignews
                                                        })


def big_news_reply_page(request):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            bignews_id = request.POST.get('bignews_id')  # from hidden input
            parent_id = request.POST.get('parent')  # from hidden input
            bignews_url = request.POST.get('bignews_url')  # from hidden input
            reply = form.save(commit=False)
    
            reply.post = Bignews(id=bignews_id)
            reply.parent = Comment(id=parent_id)
            reply.save()
            return redirect(bignews_url+'#')
    return redirect("/")

ibmn/breaking/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView , DetailView, UpdateView, TemplateView, DeleteView
from ibmn.breaking.models import Breaking
from ibmn.breaking.forms import CreateBreakForm
from django import forms


# Create your views here.

class BreakCreateView(View):
    template_name = 'manager_pages/break_add_news.html'
    form_class = CreateBreakForm
    
    def get(self, request):
        form = self.form_class()
        message = ''
        return render(request, self.template_name, context={'form': form, 'message': message})


    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return render(request,self.template_name, {'form':form})

break_create_view  =  BreakCreateView.as_view()




class BreakListPostView(LoginRequiredMixin, ListView):
    model = Breaking
    context_object_name = 'break_list'
    template_name = 'manager_pages/break_list_news.html'

break_list_view  =  BreakListPostView.as_view()



class BreakUpdateView(LoginRequiredMixin, UpdateView):
    # specify the model you want to use
    model = Breaking
    template_name = 'manager_pages/break_update_news.html'

    # specify the fields
    fields = ["text", "image"]

    def get_object(self, queryset=None):
        return Breaking.objects.get(id=self.kwargs.get("uuid"))
  
    # can specify success url
    # url to redirect after successfully
    # updating details
    def get_success_url(self):
       return reverse("news:manager_home")
   

break_update_view  = BreakUpdateView.as_view()




class BreakingManagerDeleteView(LoginRequiredMixin, DeleteView):
    # specify the model you want to use
    model = Breaking
    template_name = 'manager_pages/break_delete_news.html'

    # specify the fields
    #fields = ["title","short_txt","slug","pub_date","image","body_txt"]

    def get_object(self, queryset=None):
        return Breaking.objects.get(id=self.kwargs.get("uuid"))
  
    # can specify success url
    # url to redirect after successfully
    # updating details
    def get_success_url(self):
       return reverse("news:manager_home")
   

breaking_manager_delete_view = BreakingManagerDeleteView.as_view()

ibmn/templates/categories/health_category.html
{% extends "base.html" %}

{% load static i18n %}


{% block content %}


    <!-- Slider Section Start Here -->
    <div class="container">
        <div class="row">               
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 padding-0">
                <div class="slider-area">
                    <div class="bend niceties preview-2">
                        {% if big_news.image %}
                        <div id="ensign-nivoslider" class="slides">
                            <img src="{{big_news.image.url}}" alt="" class="calimg" title="#slider-direction-1" />                       
                        </div>
                        {% endif %} 
                        <!-- direction 2 -->
                        <div id="slider-direction-1" class="slider-direction">
                            <div class="slider-content t-cn s-tb slider-1">
                                <div class="title-container s-tb-c">
                                    <div class="slider-botton">
                                        <ul>
                                            <li>
                                                <a class="cat-link" href="{% url 'bignews:bignews_detail' big_news.slug %}">Health</a> 
                                                <span class="date"> 
                                                    <i class="fa fa-calendar-check-o" aria-hidden="true"></i>{{big_news.pub_date}}
                                                </span>
                                            </li>
                                        </ul>
                                    </div>
                                    <h1 class="title1"><a href="{% url 'bignews:bignews_detail' big_news.slug %}"> {{big_news.title}}</a></h1>
                                    <div class="title2">{{big_news.short_txt}}.</div>
                                </div>
                            </div>
                        </div>
                         <!-- direction 2 -->
                    </div>
                </div>
            </div>
            <!-- Slider  Area End Here-->

        <!-- Trending  starts Here-->


                <!--Sidebar Start Here -->
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 paddimg-left-none sidebar-latest">
                    <!--trending Post Start Here -->
                        <h3 class="title-bg">Trending News</h3>
                       <div class="hot-news trending">
                        <ul class="news-post">
                            {% for news in popular_news %}
                            <li>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 content">
                                        <div class="item-post">
                                            <div class="row">
                                                {% if big_news.image %}
                                                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-3 paddimg-right-none">
                                                    <img src="{{news.image.url}}" alt="" title="News image">
                                                </div>
                                                {% endif %} 
                                                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-9">
                                                    <h4><a href="#"> {{news.short_txt}}</a></h4>
                                                    <span class="date"><i class="fa fa-calendar-check-o" aria-hidden="true"></i> {{news.pub_date}}</span>                                                
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                            
                            
                        </ul>
                    </div> 
                    <!--popular Post End Here --> 

                    <!--Recent comments Start Here -->
                    <!--Recent comments Start Here -->
                     <!--Add Start Here -->
                  
                    <!--Add Box End Here -->          
                </div>
            </div>


            
        <!-- trending Area End Here-->


        </div>
    </div>






    <!-- Slider Section end Here -->
    <!-- All News Section Start Here -->
    

    
    <!-- Hot News Start Here -->

     <!-- Hot News Start Here -->
     <div class="hot-news">
        <div class="container">

            <div class="row">
                <div class="col-lg-12 col-md-8 col-sm-8 col-xs-12">
                    <!--Around Area Start Here -->
                        <div class="view-area separator-large3">
                                <div class="row">
                                    <div class="col-sm-8"> 
                                        <h3 class="title-bg">Global</h3>
                                    </div>
                                    <div class="col-sm-4 text-right">
                                        <a href="{% url 'categories:health_global' %}">View More <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
                                    </div>
                            </div>
                        </div> 
                        <ul class="news-post news-post2 around-news">
                        <li>
                            <div class="row">

                                {% for global_subs in global_sub  %}
                                {% for news in global_subs.categories.all|slice:"4"  %}


                                <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12 content">
                                    <div class="item-post">
                                        <div class="blog-image">
                                            {% if news.image %}
                                            <a href="{% url 'news:news_detail' news.slug %}"><img src="{{news.image.url}}" alt="" title="News image" /></a>
                                            {% endif %} 
                                        </div>
                                        <div class="content">
                                            <span class="date">
                                                <i class="fa fa-calendar-check-o" aria-hidden="true"></i>
                                                {{news.pub_date}}
                                            </span>
                                            <h4><a href="{% url 'news:news_detail' news.slug %}">{{news.short_txt|truncatechars:60}}</a></h4>
                                        </div>
                                    </div>
                                </div>

                                {% endfor %}

                                {% endfor %}

                            </div>
                        </li>
                    </ul>                   
                
                    <div class="view-area separator-large3">
                        <div class="row">
                            <div class="col-sm-8"> 
                                <h3 class="title-bg">Local</h3>
                            </div>
                            <div class="col-sm-4 text-right">
                                <a href="{% url 'categories:health_local' %}">View More <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
                            </div>
                    </div>
                </div> 
              
                <ul class="news-post news-post2 around-news">
                    <li>
                        <div class="row">

                            {% for global_subs in local_sub  %}
                            {% for news in global_subs.categories.all|slice:"4"  %}


                            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12 content">
                                <div class="item-post">
                                    <div class="blog-image">
                                        {% if news.image %}
                                        <a href="{% url 'news:news_detail' news.slug %}"><img src="{{news.image.url}}" alt="" title="News image" /></a>
                                        {% endif %} 
                                    </div>
                                    <div class="content">
                                        <span class="date">
                                            <i class="fa fa-calendar-check-o" aria-hidden="true"></i>
                                            {{news.pub_date}}
                                        </span>
                                        <h4><a href="{% url 'news:news_detail' news.slug %}">{{news.short_txt|truncatechars:60}}</a></h4>
                                    </div>
                                </div>
                            </div>

                            {% endfor %}

                            {% endfor %}

                        </div>
                    </li>
                </ul>                                
            <div class="view-area separator-large3">
                <div class="row">
                    <div class="col-sm-8"> 
                        <h3 class="title-bg">Community</h3>
                    </div>
                    <div class="col-sm-4 text-right">
                        <a href="{% url 'categories:health_community' %}">View More <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
                    </div>
            </div>
        </div> 
        <ul class="news-post news-post2 around-news">
            <li>
                <div class="row">

                    {% for global_subs in community_sub  %}
                    {% for news in global_subs.categories.all|slice:"4"  %}


                    <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12 content">
                        <div class="item-post">
                            <div class="blog-image">
                                {% if news.image %}
                                <a href="{% url 'news:news_detail' news.slug %}"><img src="{{news.image.url}}" alt="" title="News image" /></a>
                                {% endif %} 
                            </div>
                            <div class="content">
                                <span class="date">
                                    <i class="fa fa-calendar-check-o" aria-hidden="true"></i>
                                    {{news.pub_date}}
                                </span>
                                <h4><a href="{% url 'news:news_detail' news.slug %}">{{news.short_txt|truncatechars:60}}</a></h4>
                            </div>
                        </div>
                    </div>

                    {% endfor %}

                    {% endfor %}

                </div>
            </li>
        </ul>                 

    <div class="view-area separator-large3">
        <div class="row">
            <div class="col-sm-8"> 
                <h3 class="title-bg">Opinions</h3>
            </div>
            <div class="col-sm-4 text-right">
                <a href="{% url 'categories:health_opinions' %}">View More <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
            </div>
    </div>
</div> 

<ul class="news-post news-post2 around-news">
    <li>
        <div class="row">

            {% for global_subs in opinions_sub  %}
            {% for news in global_subs.categories.all|slice:"4"  %}


            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12 content">
                <div class="item-post">
                    <div class="blog-image">
                        {% if news.image %}
                        <a href="{% url 'news:news_detail' news.slug %}"><img src="{{news.image.url}}" alt="" title="News image" /></a>
                        {% endif %} 
                    </div>
                    <div class="content">
                        <span class="date">
                            <i class="fa fa-calendar-check-o" aria-hidden="true"></i>
                            {{news.pub_date}}
                        </span>
                        <h4><a href="{% url 'news:news_detail' news.slug %}">{{news.short_txt|truncatechars:60}}</a></h4>
                    </div>
                </div>
            </div>

            {% endfor %}

            {% endfor %}

        </div>
    </li>
</ul>                       
</div>
          
</div>
      
</div>
  
</div>
    
    <!-- All News Section end Here -->


{% endblock %}