config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    #path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path('', include("ibmn.news.urls")),
    path("accounts/", include("ibmn.users.urls", namespace="users")),
    path("trending/", include("ibmn.trending.urls", namespace="trending")),
    path("breaking/", include("ibmn.breaking.urls", namespace="breaking")),
    path("bignews/", include("ibmn.bignews.urls", namespace="bignews")),
    path("categories/", include("ibmn.categories.urls", namespace="categories")),
    path("ckeditor/", include('ckeditor_uploader.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ibmn/bignews/urls.py
from django.urls import include, path
from django.conf.urls import url


from ibmn.bignews.views import (bignews_create_view, bignews_update_view, big_news_details_view,
                                bignews_manager_delete_view , bignews_list_view, big_news_reply_page)


app_name = "bignews"
urlpatterns = [
    path("create/", view=bignews_create_view, name="bignews_create"),
    path('list_news/', view=bignews_list_view, name='bignews_list_post'),
    path('update/<uuid:uuid>/', view=bignews_update_view, name='bignews_update_news'),
    path('delete/<uuid:uuid>/', view= bignews_manager_delete_view, name='bignews_delete_news'),
    path("<slug:slug>/", view=big_news_details_view, name="bignews_detail"),
    path('big_comment/reply/', big_news_reply_page, name="bignews_reply"),



]

ibmn/news/urls.py
from django.urls import include, path
from django.conf.urls import url


from ibmn.news.views import (
                            home_view , manager_home_view, news_create_view,  manager_list_post_view, 
                             manager_update_view, manager_delete_view, news_details_view, reply_page,
                             search_list_news_view
                            )


app_name = "news"
urlpatterns = [
    path('', view=home_view, name="home"),
    path("create_news/", view=news_create_view, name="create"),
    path('list/', view=manager_list_post_view, name='manager_list_post'),
    path("home/", view= manager_home_view, name="manager_home"),
    path('update/<uuid:uuid>/', view=manager_update_view, name='manager_update_news'),
    path('delete/<uuid:uuid>/', view=manager_delete_view, name='manager_delete_news'),
    #path("<slug:tag_slug>/", view=news_details_view, name="news_tag_detail"),
    path("<slug:slug>/", view=news_details_view, name="news_detail"),
    path('comment/reply/', reply_page, name="reply"),
    path('list/', view=search_list_news_view, name='search'),


]

ibmn/trending/urls.py
from django.urls import include, path
from django.conf.urls import url


from ibmn.trending.views import (TrendCreateView, trend_update_view, trend_list_view,
                                  trending_news_details_view,trend_manager_delete_view ,
                                  trending_news_reply_page
                                 )


app_name = "trending"
urlpatterns = [
    path("create/", TrendCreateView.as_view(), name="trending_create"),
    path('list_trend/', view=trend_list_view, name='trend_list_post'),
    path('update/<uuid:uuid>/', view=trend_update_view, name='trend_update_news'),
    path('delete/<uuid:uuid>/', view=trend_manager_delete_view, name='trend_delete_news'),
    path("<slug:slug>/", view=trending_news_details_view, name="trendnews_detail"),
    path('trend_comment/reply/', trending_news_reply_page, name="trendnews_reply"),


    #path("<slug:slug>/", view=news_detail_view, name="news_detail"),

]

ibmn/users/urls.py
from django.urls import path
from ibmn.users.views import LoginView, logout_view



app_name = "users"
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', view=logout_view, name='logout'),

    
]

ibmn/bignews/forms.py
from unittest.util import _MAX_LENGTH
from django import forms
from django.forms import ModelChoiceField
from django.contrib.auth import authenticate
from ibmn.bignews.models import Bignews
from ibmn.categories.models import Category

from mptt.forms import TreeNodeChoiceField 
from ckeditor_uploader.widgets import  CKEditorUploadingWidget


class CreateBignewsForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text',  'data-constraints':'@Required'}))
    short_txt = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text','data-constraints':'@Required'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'id':'formFile','type':'file', 'class':'control'}))
    #slug = forms.SlugField(widget=forms.TextInput(attrs={"class": "form-control", 'type':'text'}))
   # pub_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'form-control'}))
    #category_name = forms.ModelChoiceField(queryset=Category.objects.all())
    body_txt =forms.CharField(widget=CKEditorUploadingWidget(attrs={'class':'form-control', 'rows':'5', 'cols':'50','data-constraints':'@Required'}))
   
   

    class Meta:
            model = Bignews
            fields = [
                    "title",
                    "short_txt",
                    "body_txt",
                    #"slug",
                   #"pub_date",
                    "image",
                    "category",
                    "tags"
                    ]

    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'] = forms.ModelChoiceField(queryset=Category.objects.all())

    
          

class EditBigNewsForm(forms.ModelForm):

    title = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text',  'data-constraints':'@Required'}))
    short_txt = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text','data-constraints':'@Required'}))
    #timestamp = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'id':'formFile','type':'file', 'class':'control'}))
    slug = forms.SlugField(widget=forms.TextInput(attrs={"class": "form-control", 'type':'text'}))
    #pub_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date', 'class':'form-control'}))
    category_name = forms.ModelChoiceField(queryset=Category.objects.all())
    body_txt =forms.CharField(widget=CKEditorUploadingWidget(attrs={'class':'form-control', 'rows':'5', 'cols':'50','data-constraints':'@Required'}))
    
    
   
   
    class Meta:
            model = Bignews
            fields = [
                    "title",
                    "short_txt",
                    "slug",
                    #"pub_date",
                    "image",
                    "category_name",
                    "body_txt",
                    "tags"
                    ]

ibmn/breaking/forms.py
from django import forms
from django.forms import ModelChoiceField
from django.contrib.auth import authenticate
from ibmn.breaking.models import Breaking

class CreateBreakForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text','data-constraints':'@Required'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'id':'formFile','type':'file', 'class':'control'}))

   
   
   
    class Meta:
            model = Breaking
            fields = [ "text",
                       "image",
                    ]

    

ibmn/comments/forms.py
import email
from django import forms
from ibmn.comments.models import Comment
from mptt.forms import TreeNodeChoiceField


class CommentForm(forms.ModelForm):


    name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'text',  'data-constraints':'@Required'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'type':'email',  'data-constraints':'@Required'}))
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'col':'40', 'row':'10', 'data-constraints':'@Required'}))



    class Meta:
        model = Comment
        fields = ('name',  'email', 'content')

ibmn/users/forms.py
from django import forms
from django.contrib.auth import authenticate
from ibmn.users.models import User

class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'name':'username', 'id':'yourUsername', 'type':'text','data-constraints':'@Required'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','name':'password','id':'yourPassword','type':'password','data-constraints':'@Required'}))




    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError("Account Does Not Exist.")
            if not user.check_password(password):
                raise forms.ValidationError("Password Does not Match.")
            if not user.is_active:
                raise forms.ValidationError("Account is not Active.")

        return super(UserLoginForm, self).clean(*args, **kwargs)

ibmn/bignews/views.py
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView , DetailView, UpdateView, TemplateView, DeleteView
from ibmn.bignews.models import Bignews
from ibmn.bignews.forms import CreateBignewsForm, EditBigNewsForm
from ibmn.comments.forms import CommentForm
from ibmn.comments.models import Comment



# Create your views here.

class BignewsCreateView(View):
    template_name = 'manager_pages/bignews_add_news.html'
    form_class = CreateBignewsForm
    
    def get(self, request):
        form = self.form_class()
        message = ''
        return render(request, self.template_name, context={'form': form, 'message': message})


    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            form = self.form_class()

            messages.success(request, 'Your news was successfully posted!')

        return render(request,self.template_name, {'form':form})

bignews_create_view  = BignewsCreateView.as_view()


class BignewsListPostView(LoginRequiredMixin, ListView):
    model = Bignews
    context_object_name = 'bignews_list'
    template_name = 'manager_pages/bignews_list_news.html'

bignews_list_view  =  BignewsListPostView.as_view()



class BignewsUpdateView(LoginRequiredMixin, UpdateView):
    # specify the model you want to use
    form_class = EditBigNewsForm
    model = Bignews
    template_name = 'manager_pages/bignews_update.html'

    # specify the fields
    #fields = ["title","short_txt","slug","pub_date","image","body_txt"]

    def get_object(self, queryset=None):
        return Bignews.objects.get(id=self.kwargs.get("uuid"))
  
    # can specify success url
    # url to redirect after successfully
    # updating details
    def get_success_url(self):
       return reverse("bignews:bignews_list_post")
   

bignews_update_view  = BignewsUpdateView.as_view()




class BignewsManagerDeleteView(LoginRequiredMixin, DeleteView):
    # specify the model you want to use
    model = Bignews
    template_name = 'manager_pages/bignews_delete_news.html'

    # specify the fields
    #fields = ["title","short_txt","slug","pub_date","image","body_txt"]

    def get_object(self, queryset=None):
        return Bignews.objects.get(id=self.kwargs.get("uuid"))
  
    # can specify success url
    # url to redirect after successfully
    # updating details
    def get_success_url(self):
       return reverse("bignews:bignews_list_post")
   

bignews_manager_delete_view = BignewsManagerDeleteView.as_view()






def big_news_details_view(request, slug):
    bignews=get_object_or_404(Bignews, slug=slug)

    similar_bignews =  bignews.tags.similar_objects()[:4]

    # List of active comments for this post
    bignews_comments = bignews.bignews_comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.bignews = bignews
            # Save the comment to the database
            new_comment.save()
            return redirect(bignews.get_absolute_url()+'#')
    else:
        comment_form = CommentForm()

    # List of similar posts
    
    return render(request, 'pages/bignews_details.html', {'bignews':bignews,'bignews_comments': bignews_comments,
                                                            'comment_form':comment_form, 'similar_bignews':similar_bignews
                                                        })


def big_news_reply_page(request):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            bignews_id = request.POST.get('bignews_id')  # from hidden input
            parent_id = request.POST.get('parent')  # from hidden input
            bignews_url = request.POST.get('bignews_url')  # from hidden input
            reply = form.save(commit=False)
    
            reply.post = Bignews(id=bignews_id)
            reply.parent = Comment(id=parent_id)
            reply.save()
            return redirect(bignews_url+'#')
    return redirect("/")

ibmn/breaking/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView , DetailView, UpdateView, TemplateView, DeleteView
from ibmn.breaking.models import Breaking
from ibmn.breaking.forms import CreateBreakForm
from django import forms


# Create your views here.

class BreakCreateView(View):
    template_name = 'manager_pages/break_add_news.html'
    form_class = CreateBreakForm
    
    def get(self, request):
        form = self.form_class()
        message = ''
        return render(request, self.template_name, context={'form': form, 'message': message})


    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return render(request,self.template_name, {'form':form})

break_create_view  =  BreakCreateView.as_view()




class BreakListPostView(LoginRequiredMixin, ListView):
    model = Breaking
    context_object_name = 'break_list'
    template_name = 'manager_pages/break_list_news.html'

break_list_view  =  BreakListPostView.as_view()



class BreakUpdateView(LoginRequiredMixin, UpdateView):
    # specify the model you want to use
    model = Breaking
    template_name = 'manager_pages/break_update_news.html'

    # specify the fields
    fields = ["text", "image"]

    def get_object(self, queryset=None):
        return Breaking.objects.get(id=self.kwargs.get("uuid"))
  
    # can specify success url
    # url to redirect after successfully
    # updating details
    def get_success_url(self):
       return reverse("news:manager_home")
   

break_update_view  = BreakUpdateView.as_view()




class BreakingManagerDeleteView(LoginRequiredMixin, DeleteView):
    # specify the model you want to use
    model = Breaking
    template_name = 'manager_pages/break_delete_news.html'

    # specify the fields
    #fields = ["title","short_txt","slug","pub_date","image","body_txt"]

    def get_object(self, queryset=None):
        return Breaking.objects.get(id=self.kwargs.get("uuid"))
  
    # can specify success url
    # url to redirect after successfully
    # updating details
    def get_success_url(self):
       return reverse("news:manager_home")
   

breaking_manager_delete_view = BreakingManagerDeleteView.as_view()

ibmn/templates/pages/about.html
{% extends "base.html" %}

ibmn/templates/pages/bignews_comment.html
<div class="border-0 border-start border-2 ps-2" id="{{comment.id}}">

    <div class="mt-3">
        <strong>{{comment.name}}</strong> 
        {% if  comment.parent.name%} replied to <strong>{{comment.parent.name}}</strong>{% endif %}
        <small class="text-muted">On {{ comment.pub_date.date }}</small>

    </div>
        <p>{{comment.content}}</p>
        <button class="btn btn-danger btn-sm" onclick="handleReply({{comment.id}})">Reply</button>
    
        <div id="reply-form-container-{{comment.id}}" style="display:none">
        
            <form method="post" action="{% url 'bignews:bignews_reply' %}" class="mt-3">
                {% csrf_token %}
                
                 <fieldset>
                <input type="hidden" name="bignews_id" value="{{bignews.id}}">
                <input type="hidden" name="parent" value="{{comment.id}}">
                <input type="hidden" name="bignews_url" value="{{bignews.get_absolute_url}}">
                        <div class="form-group">
                            <label>Name*</label>
                            {{comment_form.name}}
                        </div>
                        <div class="form-group">
                            <label>Email*</label>
                            {{comment_form.email}}
                        </div>
                        <div class="form-group">
                            <label>Your comment here...</label>
                            {{comment_form.content}}
                        </div>
                        <div class="form-group">
                            <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-danger btn-sm">Cancel</button>
                            <button class="btn btn-danger btn-sm" type="submit">Make Comment</button>
                        </div>
                    </fieldset>
            </form>
        </div>
    {% for comment in comment.get_comments %}
        {% include 'pages/bignews_comment.html' with comment=comment %}
    {% endfor %}
</div>

ibmn/templates/pages/bignews_details.html
{% extends "base2.html" %}

{% load static i18n %}
{% load social_share %}


{% block content %}
<!-- Blog Single Start Here -->
<div class="single-blog-page-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <div class="single-image">
                    {% if bignews.image %}
                    <img src="{{bignews.image.url}}" alt="Blog single photo" />
                    {% endif %} 
                </div>
                <h3>{{bignews.short_txt}}</h3>

                {{bignews.body_txt|safe}}

                
                  <div class="share-section">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 life-style">
                            
                            <span class="author"> 
                                <a href="#"><i class="fa fa-user-o" aria-hidden="true"></i>{{request.user.get_full_name}} </a>
                            </span> 
                            <span class="date">
                                <i class="fa fa-calendar-check-o" aria-hidden="true"></i>{{bignews.pub_date.date}}
                            </span>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <ul class="share-link">
                                <li class="hvr-bounce-to-right"><a href="#"> Tags:</a></li>
                                {% for tag in bignews.tags.all|slice:"2" %}
                                <li class="hvr-bounce-to-right"><a href="#">{{ tag }}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>

                <div class="share-section share-section2">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <span> You Can Share It : </span>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <ul class="share-link">
                               <li class="hvr-bounce-to-right"> {% post_to_facebook object_or_url "Facebook" %} </li> 
                               <li class="hvr-bounce-to-right"> {% post_to_whatsapp object_or_url "Whatsapp" %} </li> 
                               <li class="hvr-bounce-to-right"> {% post_to_twitter object_or_url "Twitter" %} </li> 

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="author-comment">
                    <h3 class="title-bg">Recent Comments</h3>
                        {% with bignews_comments.count as total_bignews_comments %}
                        <h3 class="title-sm">
                            {{ total_bignews_comments }} comment{{ total_bignews_comments|pluralize }}
                        </h3>
                          {% endwith %}
                            
                            {% if not bignews.bignews_comments.all %}
                            No comments yet
                            {% else %}
                                {% for comment in bignews.get_comments %}
                                {% include 'pages/bignews_comment.html' with comment=comment %}
                            {% endfor %}
                            {% endif %}
                        
                      </div>            
                       <div class="leave-comments-area">
                        <h4 class="title-bg">Leave Comments</h4>
                        <form  id="myForm" method="post" >
                            {% csrf_token %}
                            <fieldset>
                                <div class="form-group">
                                    <label>Name*</label>
                                    {{comment_form.name}}
                                </div>
                                <div class="form-group">
                                    <label>Email*</label>
                                    {{comment_form.email}}
                                </div>
                                <div class="form-group">
                                    <label>Your comment here...</label>
                                    {{comment_form.content}}
                                </div>
                                <div class="form-group">
                                    <button class="btn-send" type="submit">Make Comment</button>
                                </div>
                            </fieldset>
                       </form>
                </div>  
                                
                                             
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <!-- Blog Single Sidebar Start Here -->
                <div class="sidebar-area">
                   
                    <div class="recent-post-area hot-news">
                        <h3 class="title-bg">Related News</h3>
                        <ul class="news-post">
                            {% for news in similar_bignews%}
                            <li> 
                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 content">
                                    <div class="item-post">
                                        <div class="row">
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 paddimg-right-none">
                                                {% if news.image %}
                                                <a href="{% url 'news:news_detail' news.slug %}"><img src="{{news.image.url}}" alt="" title="News image" /></a>
                                                {% endif %} 
                                            </div>
                                            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                                                <h4><a href="{% url 'news:news_detail' news.slug %}">{{news.short_txt|truncatechars:60}}                                                    </a></h4>
                                                <span class="date"><i class="fa fa-calendar-check-o" aria-hidden="true"></i>{{news.pub_date}}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                            {% endfor %}
                        </ul>
                    </div>
                   
                </div>
            </div>                
        </div>
    </div>
</div>
<!-- Blog Details Page end here -->

{% endblock %}

ibmn/templates/pages/comment.html
<div class="border-0 border-start border-2 ps-2" id="{{comment.id}}">

    <div class="mt-3">
        <strong>{{comment.name}}</strong> 
        {% if  comment.parent.name%} replied to <strong>{{comment.parent.name}}</strong>{% endif %}
        <small class="text-muted">On {{ comment.pub_date.date }}</small>

    </div>
        <p>{{comment.content}}</p>
        <button class="btn btn-danger btn-sm" onclick="handleReply({{comment.id}})">Reply</button>
    
        <div id="reply-form-container-{{comment.id}}" style="display:none">
        
            <form method="post" action="{% url 'news:reply' %}" class="mt-3">
                {% csrf_token %}
                
                 <fieldset>
                <input type="hidden" name="news_id" value="{{news.id}}">
                <input type="hidden" name="parent" value="{{comment.id}}">
                <input type="hidden" name="news_url" value="{{news.get_absolute_url}}">
                        <div class="form-group">
                            <label>Name*</label>
                            {{comment_form.name}}
                        </div>
                        <div class="form-group">
                            <label>Email*</label>
                            {{comment_form.email}}
                        </div>
                        <div class="form-group">
                            <label>Your comment here...</label>
                            {{comment_form.content}}
                        </div>
                        <div class="form-group">
                            <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-danger btn-sm">Cancel</button>
                            <button class="btn btn-danger btn-sm" type="submit">Make Comment</button>
                        </div>
                    </fieldset>
            </form>
        </div>
    {% for comment in comment.get_comments %}
        {% include 'pages/comment.html' with comment=comment %}
    {% endfor %}
</div>

ibmn/templates/pages/commente.html
<div class="border-0 border-start border-2 ps-2" id="{{comment.id}}">

    <div class="mt-3">
        <strong>{{comment.name}}</strong> 
        {% if  comment.parent.name%} to <strong>{{comment.parent.name}}</strong>{% endif %}
        <small class="text-muted">On {{ comment.created.date }}</small>
    </div>
        <p>{{comment.content}}</p>
        <button class="btn btn-primary btn-sm" onclick="handleReply({{comment.id}})">Reply</button>
    
        <div id="reply-form-container-{{comment.id}}" style="display:none">
        
            <form method="post" action="{% url 'news:reply' %}" class="mt-3">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{news.id}}">
                <input type="hidden" name="parent" value="{{comment.id}}">
                <input type="hidden" name="post_url" value="{{news.get_absolute_url}}">


                {{comment_form.as_p}}

                <div>
                    <button type="button" onclick="handleCancel({{comment.id}})" class="btn btn-light border btn-sm">Cancel</button>
                    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
                </div>
            </form>
        </div>
    {% for comment in comment.get_comments %}
        {% include 'commente.html' with comment=comment %}
    {% endfor %}
</div>